let strip = neopixel.create(DigitalPin.P1, 25, NeoPixelMode.RGB)
let achtergrondkleur = neopixel.hsl(205, 100, 68)
strip.showColor(neopixel.colors(NeoPixelColors.Green))
let rij1 = strip.range(1, 3)
let led9 = strip.range(9, 1)
let led5 = strip.range(5, 1)
let led16 = strip.range(16, 1)
let led18 = strip.range(18, 1)
let led0 = strip.range(0, 1)
let led4 = strip.range(4, 1)
let rij2 = strip.range(6, 3)
rij1.showColor(neopixel.colors(NeoPixelColors.Violet))
led9.showColor(neopixel.colors(NeoPixelColors.Violet))
led5.showColor(neopixel.colors(NeoPixelColors.Violet))
led16.showColor(neopixel.colors(NeoPixelColors.Yellow))
led18.showColor(neopixel.colors(NeoPixelColors.Yellow))
for (let index = 0; index < 4; index++) {
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    led16.showColor(neopixel.colors(NeoPixelColors.Violet))
    led18.showColor(neopixel.colors(NeoPixelColors.Violet))
    led0.showColor(neopixel.colors(NeoPixelColors.Yellow))
    led4.showColor(neopixel.colors(NeoPixelColors.Yellow))
    rij2.showColor(neopixel.colors(NeoPixelColors.Yellow))
    rij1.showColor(neopixel.colors(NeoPixelColors.Green))
    led5.showColor(neopixel.colors(NeoPixelColors.Green))
    led9.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(2000)
    led18.showColor(neopixel.colors(NeoPixelColors.Yellow))
    led16.showColor(neopixel.colors(NeoPixelColors.Yellow))
    rij1.showColor(neopixel.colors(NeoPixelColors.Violet))
    led5.showColor(neopixel.colors(NeoPixelColors.Violet))
    led9.showColor(neopixel.colors(NeoPixelColors.Violet))
    led0.showColor(neopixel.colors(NeoPixelColors.Green))
    led4.showColor(neopixel.colors(NeoPixelColors.Green))
    rij2.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(2000)
    for (let index = 0; index < 25; index++) {
        strip.shift(1)
        basic.pause(100)
    }
}
